# Use official Bun image
FROM oven/bun:latest

# Set working directory
WORKDIR /app

# Copy package files first for better caching
# COPY bun.lockb package.json ./

COPY  package.json src/ ./

# Install dependencies
RUN bun install

# Copy the rest of the project

# Start Vite dev server
# CMD ["bun", "install"]

