version: '3.9'

services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "51204:51204"
    volumes:
      - .:/app
    # command: bunx vitest --ui --open=false
    command: bunx vitest

